-- CROTI Portfolio CMS
-- Execute este arquivo inteiro no SQL Editor do Supabase.

create extension if not exists pgcrypto;

create table if not exists public.admins (
    user_id uuid primary key references auth.users(id) on delete cascade,
    created_at timestamptz not null default now()
);

create or replace function public.is_croti_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.admins where user_id = auth.uid()
    );
$$;

revoke all on function public.is_croti_admin() from public;
grant execute on function public.is_croti_admin() to anon, authenticated;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create table if not exists public.portfolio_videos (
    id uuid primary key default gen_random_uuid(),
    title text not null check (char_length(title) between 1 and 100),
    client text not null default '' check (char_length(client) <= 100),
    category text not null check (category in ('featured', 'short', 'vsl')),
    description text not null default '' check (char_length(description) <= 500),
    year integer not null default (extract(year from current_date)::integer) check (year between 2000 and 2100),
    services text[] not null default '{}',
    aspect text not null default 'horizontal' check (aspect in ('horizontal', 'vertical')),
    media_position text not null default '50% 50%' check (char_length(media_position) <= 40),
    video_path text not null unique,
    poster_path text,
    sort_order integer not null default 0 check (sort_order >= 0),
    published boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.portfolio_clients (
    id uuid primary key default gen_random_uuid(),
    name text not null check (char_length(name) between 1 and 100),
    platform text not null default 'instagram' check (platform in ('instagram', 'youtube', 'tiktok')),
    instagram_url text not null check (char_length(instagram_url) between 10 and 300),
    instagram_handle text not null check (char_length(instagram_handle) between 1 and 60),
    followers_count bigint not null default 0 check (followers_count >= 0),
    profile_path text,
    sort_order integer not null default 0 check (sort_order >= 0),
    published boolean not null default true,
    verified boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.portfolio_testimonials (
    id uuid primary key default gen_random_uuid(),
    quote text not null check (char_length(quote) between 10 and 600),
    name text not null check (char_length(name) between 1 and 100),
    role text not null default '' check (char_length(role) <= 120),
    profile_path text,
    sort_order integer not null default 0 check (sort_order >= 0),
    published boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.leads (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(name) between 2 and 100),
    whatsapp text not null check (char_length(whatsapp) between 6 and 30),
    email text not null check (char_length(email) between 5 and 254),
    source text not null default 'portfolio',
    created_at timestamptz not null default now()
);

-- Migrações idempotentes para instalações que usaram versões anteriores.
alter table public.portfolio_videos add column if not exists year integer not null default (extract(year from current_date)::integer);
alter table public.portfolio_videos add column if not exists services text[] not null default '{}';
alter table public.portfolio_videos add column if not exists aspect text not null default 'horizontal';
alter table public.portfolio_videos add column if not exists media_position text not null default '50% 50%';
alter table public.portfolio_clients add column if not exists platform text not null default 'instagram';

drop trigger if exists portfolio_videos_set_updated_at on public.portfolio_videos;
create trigger portfolio_videos_set_updated_at
before update on public.portfolio_videos
for each row execute function public.set_updated_at();

drop trigger if exists portfolio_clients_set_updated_at on public.portfolio_clients;
create trigger portfolio_clients_set_updated_at
before update on public.portfolio_clients
for each row execute function public.set_updated_at();

drop trigger if exists portfolio_testimonials_set_updated_at on public.portfolio_testimonials;
create trigger portfolio_testimonials_set_updated_at
before update on public.portfolio_testimonials
for each row execute function public.set_updated_at();

create index if not exists portfolio_videos_public_order_idx on public.portfolio_videos (published, sort_order, created_at desc);
create index if not exists portfolio_clients_public_order_idx on public.portfolio_clients (published, sort_order, created_at desc);
create index if not exists portfolio_testimonials_public_order_idx on public.portfolio_testimonials (published, sort_order, created_at desc);

alter table public.admins enable row level security;
alter table public.portfolio_videos enable row level security;
alter table public.portfolio_clients enable row level security;
alter table public.portfolio_testimonials enable row level security;
alter table public.leads enable row level security;

drop policy if exists "Published videos are public" on public.portfolio_videos;
create policy "Published videos are public"
on public.portfolio_videos for select
using (published or public.is_croti_admin());

drop policy if exists "Admins manage videos" on public.portfolio_videos;
create policy "Admins manage videos"
on public.portfolio_videos for all
to authenticated
using (public.is_croti_admin())
with check (public.is_croti_admin());

drop policy if exists "Published clients are public" on public.portfolio_clients;
create policy "Published clients are public"
on public.portfolio_clients for select
using (published or public.is_croti_admin());

drop policy if exists "Admins manage clients" on public.portfolio_clients;
create policy "Admins manage clients"
on public.portfolio_clients for all
to authenticated
using (public.is_croti_admin())
with check (public.is_croti_admin());

drop policy if exists "Published testimonials are public" on public.portfolio_testimonials;
create policy "Published testimonials are public"
on public.portfolio_testimonials for select
using (published or public.is_croti_admin());

drop policy if exists "Admins manage testimonials" on public.portfolio_testimonials;
create policy "Admins manage testimonials"
on public.portfolio_testimonials for all
to authenticated
using (public.is_croti_admin())
with check (public.is_croti_admin());

drop policy if exists "Visitors create leads" on public.leads;
create policy "Visitors create leads"
on public.leads for insert
to anon, authenticated
with check (
    source = 'portfolio'
    and char_length(name) between 2 and 100
    and char_length(whatsapp) between 6 and 30
    and char_length(email) between 5 and 254
);

drop policy if exists "Admins read leads" on public.leads;
create policy "Admins read leads"
on public.leads for select
to authenticated
using (public.is_croti_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'portfolio-media',
    'portfolio-media',
    true,
    52428800,
    array['video/mp4', 'video/webm', 'image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public portfolio media" on storage.objects;
create policy "Public portfolio media"
on storage.objects for select
using (bucket_id = 'portfolio-media');

drop policy if exists "Admins upload portfolio media" on storage.objects;
create policy "Admins upload portfolio media"
on storage.objects for insert
to authenticated
with check (bucket_id = 'portfolio-media' and public.is_croti_admin());

drop policy if exists "Admins update portfolio media" on storage.objects;
create policy "Admins update portfolio media"
on storage.objects for update
to authenticated
using (bucket_id = 'portfolio-media' and public.is_croti_admin())
with check (bucket_id = 'portfolio-media' and public.is_croti_admin());

drop policy if exists "Admins delete portfolio media" on storage.objects;
create policy "Admins delete portfolio media"
on storage.objects for delete
to authenticated
using (bucket_id = 'portfolio-media' and public.is_croti_admin());

-- Analytics & Settings
create table if not exists public.site_settings (
    key text primary key,
    value text not null,
    updated_at timestamptz not null default now()
);

create table if not exists public.analytics_page_views (
    id uuid primary key default gen_random_uuid(),
    path text not null default '/',
    created_at timestamptz not null default now()
);

create table if not exists public.analytics_clicks (
    id uuid primary key default gen_random_uuid(),
    button_name text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.analytics_video_views (
    id uuid primary key default gen_random_uuid(),
    video_id uuid not null references public.portfolio_videos(id) on delete cascade,
    watch_percentage integer not null check (watch_percentage between 0 and 100),
    created_at timestamptz not null default now()
);

alter table public.portfolio_videos add column if not exists likes_count integer not null default 0;

alter table public.site_settings enable row level security;
alter table public.analytics_page_views enable row level security;
alter table public.analytics_clicks enable row level security;
alter table public.analytics_video_views enable row level security;

create policy "Public read settings" on public.site_settings for select using (true);
create policy "Admins manage settings" on public.site_settings for all to authenticated using (public.is_croti_admin()) with check (public.is_croti_admin());

create policy "Anon insert page views" on public.analytics_page_views for insert to anon, authenticated with check (true);
create policy "Admins read page views" on public.analytics_page_views for select to authenticated using (public.is_croti_admin());

create policy "Anon insert clicks" on public.analytics_clicks for insert to anon, authenticated with check (true);
create policy "Admins read clicks" on public.analytics_clicks for select to authenticated using (public.is_croti_admin());

create policy "Anon insert video views" on public.analytics_video_views for insert to anon, authenticated with check (true);
create policy "Admins read video views" on public.analytics_video_views for select to authenticated using (public.is_croti_admin());

create or replace function public.increment_video_likes(p_video_id uuid)
returns void
language sql
security definer
as $$
    update public.portfolio_videos
    set likes_count = likes_count + 1
    where id = p_video_id;
$$;
grant execute on function public.increment_video_likes(uuid) to anon, authenticated;

-- ETAPA FINAL:
-- 1. Crie o usuário em Authentication > Users.
-- 2. Copie o UUID e execute a linha abaixo substituindo o valor.
-- insert into public.admins (user_id) values ('UUID_DO_SEU_USUARIO') on conflict do nothing;
